# application-dev.yaml的模板配置文件
# 配置springboot的模板环境
# 配置模板
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/felLeagueHome
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  mail:
    username: youname@name.com
    password: your password
    host: smtp.name.com
    port: 25
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
  config:
    name: YourApplicationName
logging:
  level:
    com.flashlack.felleaguehome: DEBUG